# Generated by Django 5.1 on 2024-08-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen', models.CharField(max_length=200)),
                ('moves', models.CharField(max_length=200)),
                ('lichess_puzzle', models.CharField(max_length=100)),
            ],
        ),
    ]
