# Generated by Django 5.1 on 2024-09-06 02:08

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_gameroom_in_progress_alter_gameroom_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='current_puzzle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puzzle_in_progress', to='api.puzzle'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='room_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
