# Generated by Django 5.1 on 2024-09-06 02:28

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_gameroom_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='current_puzzle',
        ),
        migrations.AddField(
            model_name='gameroom',
            name='current_puzzle_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='room_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
