# Generated by Django 5.1 on 2024-09-06 02:47

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_gameroom_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='current_puzzle_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='room_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
