# Generated by Django 5.1 on 2024-09-14 19:39

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_gameroom_room_name_alter_gameroom_target_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='got_first',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='got_second',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='got_third',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='room_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
