# Generated by Django 5.1 on 2024-09-19 23:38

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_profile_games_played_profile_got_first_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='rating',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='room_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
